/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.vezbanje;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author acer e1
 */
public class FMatematickaOperacija extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form FMatematickaOperacija
     */
    public FMatematickaOperacija() {
        initComponents();
        postaviOsluskivac();
        postaviModel();
        postaviOkvir();
//        setBounds(new java.awt.Rectangle(200, 200, 500, 400));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelX = new javax.swing.JLabel();
        jTextFieldX = new javax.swing.JTextField();
        jLabelY = new javax.swing.JLabel();
        jTextFieldY = new javax.swing.JTextField();
        jLabelRez = new javax.swing.JLabel();
        jTextFieldRez = new javax.swing.JTextField();
        jButtonOduzmi = new javax.swing.JButton();
        jButtonSaberi = new javax.swing.JButton();
        jComboBoxMatOperacija = new javax.swing.JComboBox<>();
        jButtonAkcija = new javax.swing.JButton();
        jLabelKeyPressed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forma : Matematicka Operacija");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelX.setText("Polje x :");

        jLabelY.setText("Polje y :");

        jTextFieldY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldYKeyPressed(evt);
            }
        });

        jLabelRez.setText("Rezultat :");

        jTextFieldRez.setEditable(false);

        jButtonOduzmi.setText("Oduzmi");

        jButtonSaberi.setText("Saberi");

        jButtonAkcija.setText("Akcija");
        jButtonAkcija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAkcijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonAkcija)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelX)
                                .addGap(77, 77, 77)
                                .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelRez)
                                .addGap(69, 69, 69)
                                .addComponent(jTextFieldRez, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSaberi)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonOduzmi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxMatOperacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelY)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKeyPressed, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelX))
                    .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelY))
                    .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKeyPressed, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelRez))
                    .addComponent(jTextFieldRez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSaberi)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonOduzmi)
                        .addComponent(jComboBoxMatOperacija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButtonAkcija)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldYKeyPressed
        jTextFieldY.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    int x = Integer.parseInt(jTextFieldX.getText().trim());
                    int y = Integer.parseInt(jTextFieldY.getText().trim());
                    jTextFieldRez.setText(String.valueOf(x + y));
                    Thread trd = new Thread() {
                        public void run() {
                            jLabelKeyPressed.setText(" desio se dogadjaj, pritisnuli ste enter ");
                            try {
                                Thread.sleep(3000);
                                jLabelKeyPressed.setText("");
                            } catch (InterruptedException ex) {
                                Logger.getLogger(FMatematickaOperacija.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    };
                    trd.start();
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });

    }//GEN-LAST:event_jTextFieldYKeyPressed

    private void jButtonAkcijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAkcijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAkcijaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAkcija;
    private javax.swing.JButton jButtonOduzmi;
    private javax.swing.JButton jButtonSaberi;
    private javax.swing.JComboBox<String> jComboBoxMatOperacija;
    private javax.swing.JLabel jLabelKeyPressed;
    private javax.swing.JLabel jLabelRez;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JTextField jTextFieldRez;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldY;
    // End of variables declaration//GEN-END:variables
    private void postaviOsluskivac() {
        jButtonSaberi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Integer.parseInt(jTextFieldX.getText().trim());
                int y = Integer.parseInt(jTextFieldY.getText().trim());
                jTextFieldRez.setText(String.valueOf(x + y));
            }
        });

        jButtonOduzmi.addActionListener((ActionEvent e) -> {
            int x1 = Integer.parseInt(jTextFieldX.getText().trim());
            int y1 = Integer.parseInt(jTextFieldY.getText().trim());
            jTextFieldRez.setText(String.valueOf(x1 - y1));
        });

        jButtonAkcija.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int x = Integer.parseInt(jTextFieldX.getText().trim());
                int y = Integer.parseInt(jTextFieldY.getText().trim());
                switch (jComboBoxMatOperacija.getSelectedItem().toString()) {
                    case "+":
                        jTextFieldRez.setText(saberi(x, y));
                        break;
                    case "-":
                        jTextFieldRez.setText(oduzmi(x, y));
                        break;
                    case "*":
                        jTextFieldRez.setText(pomnozi(x, y));
                        break;
                    case "/":
                        jTextFieldRez.setText(podeli(x, y));
                        break;
                }
            }

            private String saberi(int x, int y) {
                return String.valueOf(x + y);
            }

            private String oduzmi(int x, int y) {
                return String.valueOf(x - y);
            }

            private String pomnozi(int x, int y) {
                return String.valueOf(x * y);
            }

            private String podeli(int x, int y) {
                return String.valueOf(x / y);
            }
        });
    }

    /**
     * Metoda koja postavlja JComboBoxoperacije
     */
    private void postaviModel() {
        new ModelOperacija(jComboBoxMatOperacija);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        Object source = e.getSource();
        if (source instanceof JButton) {
            int a = Integer.parseInt(jTextFieldX.getText().trim());
            int b = Integer.parseInt(jTextFieldY.getText().trim());
            JButton button = (JButton) source;
            if (button.getText().equalsIgnoreCase("Saberi")) {
                jTextFieldRez.setText((a + b) + "");
            } else {
                jTextFieldRez.setText((a - b) + "");
            }
        }
    }
    //    private void postaviOsluskivac(){
//    jButtonSaberi.addActionListener(this);
//    jButtonOduzmi.addActionListener(this);
//    }

    /**
     * Metoda koja podesava GUI na sredinu ekrana
     */
    void postaviOkvir() {
        setSize(400, 300);
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        int width = (int) toolkit.getScreenSize().getWidth();
        int height = (int) toolkit.getScreenSize().getHeight();
//        setSize(width, height);
        int x = (width - getWidth()) / 2;
        int y = (height - getHeight()) / 2;
        setBounds(x, y, getWidth(), getHeight());
    }

}
